########################
### bashrc from Marc ###
########################

CHAR="\[\033[1;93m\]$\[\033[m\]"
NAME="\[\033[1;32m\]\u\[\033[m\]"
HOST="\[\033[0;37m\]\h\[\033[m\]"
DIR="\[\033[1;94m\]\w\[\033[m\]"
export PS1="${NAME}@${HOST}:${DIR} ${CHAR} "

# dotfile management
alias dotdrop="~/dotfiles/dotdrop.sh --cfg=~/dotfiles/config.yaml"

# shortcuts
alias ..="cd .."
alias ll="ls -l"
alias la="ls -la"

# Source global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi
