########################
### bashrc from Marc ###
########################

PS2="\n>"
NAME="\[\033[0;32m\]\u\[\033[m\]"
DIR="\[\033[1;34m\]\w\[\033[m\]"
export PS1="${NAME}@\h: ${DIR} ${PS2} "

# Colored Files
LS_COLORS=$LS_COLORS:'di=1;32:'
export LS_COLORS

# dotfile management
alias dotdrop="~/dotfiles/dotdrop.sh --cfg=~/dotfiles/config.yaml"

# shortcuts
alias ..="cd .."
alias ll="ls -l"
alias la="ls -la"

# Source global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi
