export TERM="xterm-256color"
xrdb -load $HOME/.Xresources
export SHELL="/bin/zsh"

setxkbmap -layout za

picom &

export LANG="en_US.UTF-8"
export LANGUAGE="en_US.UTF-8"

{%@@ if profile == "work" @@%}
/share/bin/isda
~/bin/.keyboard.scm &
xrandr --output HDMI-2 --auto --right-of HDMI-1
feh --bg-scale ~/.wallpaper/wallpaper_genuaW.png
i3
{%@@ endif @@%}

{%@@ if profile == "laptop" @@%}
feh --bg-scale ~/.wallpaper/wallpaper.png
i3
{%@@ endif @@%}
