export ZSH="/home/$USER/.oh-my-zsh"

ZSH_THEME="the-one"

DISABLE_AUTO_UPDATE="true"
COMPLETION_WAITING_DOTS="true"
DISABLE_UNTRACKED_FILES_DIRTY="true"

plugins=(
  git
  common-aliases
  compleat
  history
)

source $ZSH/oh-my-zsh.sh
export TERM="xterm-256color"
export EDITOR="vim"

export LANG="en_US.UTF-8"

# Some aliases
alias zshrc="vim ~/.zshrc"
alias szsh="source ~/.zshrc"

alias dotf="cd ~/dotfiles/dotfiles"

alias vimrc="vim ~/.vimrc"

alias dotdrop="~/dotfiles/dotdrop.sh" --cfg="~/dotfiles/config.yaml"

alias screenshot="import ~/Downloads/Screenshot-$(date '+%Y%m%d-%H%M%S').png"

alias fonts="/home/$USER/.local/share/fonts"
alias listfonts="fc-list :scalable=true:spacing=mono: family"
alias cachefonts="fc-cache -f -v"

if [ -f ~/.zshaliases_local ]; then
    source ~/.zshaliases_local
fi
