export ZSH="/home/$USER/.oh-my-zsh"
ZSH_THEME="agnoster-plus"
DISABLE_AUTO_UPDATE="true"
COMPLETION_WAITING_DOTS="true"
DISABLE_UNTRACKED_FILES_DIRTY="true"

plugins=(
  git
  common-aliases
  compleat
  history
)

source $ZSH/oh-my-zsh.sh
export TERM="xterm-256color"
export EDITOR="vim"

# Some aliases
alias zshrc="vim ~/.zshrc"
alias szsh="source ~/.zshrc"

alias vimrc="vim ~/.vimrc"

alias dotdrop="~/dotfiles/dotdrop.sh" --cfg="~/dotfiles/config.yaml"

alias fonts="/home/$USER/.local/share/fonts"
alias listfonts="fc-list :scalable=true:spacing=mono: family"
alias cachefonts="fc-cache -f -v"
