xrdb -load $HOME/.Xresources
export SHELL="/bin/zsh"

setxkbmap -layout za

export LANG="en_US.UTF-8"
export LANGUAGE="en_US.UTF-8"

{%@@ if profile == "work" @@%}
export TERM="xterm-256color"
/share/bin/isda
~/bin/.keyboard.scm &
xrandr --output HDMI-2 --auto --right-of HDMI-1
compton &
i3
{%@@ endif @@%}
